### ISSUE TITLE
Don't fail fatally when including non-existent files

### ISSUE THREAD

**Issue by Keno** [Keno/Cxx.jl#60]
Including a non-existent file will give a fatal error, which prevents clang from emitting any further diagnostics. We should downgrade this to an error somehow.

**Comment by andreasnoack** [comment]
I'm trying to see if I can wrap some of the linear algebra library Elemental with your package and I'm getting an error that might be related to this issue
```julia
julia> cxx""" #include</Users/andreasnoack/Elemental/build/include/El.hpp> """
In file included from :1:
__cxxjl_0.cpp:1:10: error: 'El.hpp' file not found with <angled> include; use "quotes" instead
 #include<El.hpp> 
         ^~~~~~~~
         "El.hpp"
In file included from :1:
In file included from __cxxjl_0.cpp:1:
In file included from ./El.hpp:18:
./El/core.hpp:105:10: fatal error: 'El/core/Timer.hpp' file not found
#include "El/core/Timer.hpp"
         ^
Assertion failed: (!ASTTy->isIncompleteType() && "Unexpected incomplete type"), function EmitGlobalVarDefinition, file /Users/andreasnoack/julia-dev/deps/llvm-svn/tools/clang/lib/CodeGen/CodeGenModule.cpp, line 1976.

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Abort trap: 6
```
My issue could probably go away if clang could find `Timer.hpp`. Is there a way to add to the header file path in your package?

**Comment by Keno** [comment]
Sorry Andreas, I didn't see your question here at all. I hope you were able to figure it out. In any case, this bug is now fixed by resetting the diagnostic engine.

**Comment by goretkin** [comment]
I still get a segfault when clang prints out `fatal error: '[somefile]' file not found`
